[tool.poetry]
name = "pyboost"
version = "0.1.0"
description = "Ferramenta de linha de comando (CLI) que visa acelerar o desenvolvimento de aplicativos em Python."
authors = ["Nícolas Albuquerque Ramos <nicolasalbuquerque581@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
