"""
Django settings for project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from dynaconf import DjangoDynaconf, Validator  # noqa

PROJECT_NAME = ''

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# A list of validators to be triggered right after the Dynaconf
# initialization.
_allowed_environments = (
    'development',
    'testing',
    'production',
)

_validators = [
    Validator('ENV', must_exist=True),
    Validator('DEBUG', is_type_of=bool),
    Validator('ENV', is_in=_allowed_environments),
]

settings = DjangoDynaconf(
    __name__,
    settings_files=[
        "settings.yaml",
        ".secrets.yaml",
    ],
    # set the variable to switch environment
    env_switcher=f'{PROJECT_NAME.upper()}_ENV',
    envvar_prefix=PROJECT_NAME.upper(),
    load_dotenv=False,
    validators=_validators,
)
